Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data  # Feature matrix as NumPy array
feature_names = iris.feature_names

# Calculate mean, median, standard deviation, and variance
means = np.mean(X, axis=0)
medians = np.median(X, axis=0)
std_devs = np.std(X, axis=0)
variances = np.var(X, axis=0)

# Identify which feature has the highest variability
variability = variances
highest_variability = feature_names[np.argmax(variability)]

# Convert one feature into shape (n,1)
sepal_length_reshaped = X[:, 0].reshape(-1, 1)

# Results
means, medians, std_devs, variances, highest_variability, sepal_length_reshaped.shape

(array([5.84333333, 3.05733333, 3.758     , 1.19933333]),
 array([5.8 , 3.  , 4.35, 1.3 ]),
 array([0.82530129, 0.43441097, 1.75940407, 0.75969263]),
 array([0.68112222, 0.18871289, 3.09550267, 0.57713289]),
 'petal length (cm)',
 (150, 1))

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [2]:
# Extract first 100 samples and last 2 features
X_subset = X[:100, -2:]

# Compute mean of petal length
mean_petal_length = np.mean(X[:, 2])

# Use boolean masking to select samples where petal length is greater than the mean
selected_samples = X_subset[X_subset[:, 0] > mean_petal_length]

# Count selected samples
count_selected = selected_samples.shape[0]

# Results
count_selected

43

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [3]:
# Apply standardization
X_standardized = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

# Verify mean and standard deviation
mean_verification = np.mean(X_standardized, axis=0)
std_verification = np.std(X_standardized, axis=0)

# Results
mean_verification, std_verification

(array([-1.69031455e-15, -1.84297022e-15, -1.69864123e-15, -1.40924309e-15]),
 array([1., 1., 1., 1.]))

Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [4]:
import seaborn as sns

# Load the Titanic dataset
titanic = sns.load_dataset('titanic')

# Display head, tail, info, describe
head = titanic.head()
tail = titanic.tail()
info = titanic.info()
description = titanic.describe()

# Identify missing values
missing_values = titanic.isnull().sum()

# Results
head, tail, info, description, missing_values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


(   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
 0         0       3    male  22.0      1      0   7.2500        S  Third   
 1         1       1  female  38.0      1      0  71.2833        C  First   
 2         1       3  female  26.0      0      0   7.9250        S  Third   
 3         1       1  female  35.0      1      0  53.1000        S  First   
 4         0       3    male  35.0      0      0   8.0500        S  Third   
 
      who  adult_male deck  embark_town alive  alone  
 0    man        True  NaN  Southampton    no  False  
 1  woman       False    C    Cherbourg   yes  False  
 2  woman       False  NaN  Southampton   yes   True  
 3  woman       False    C  Southampton   yes  False  
 4    man        True  NaN  Southampton    no   True  ,
      survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
 886         0       2    male  27.0      0      0  13.00        S  Second   
 887         1       1  female  19.0      0      

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [5]:
# Filter female passengers in 1st class
female_first_class = titanic[(titanic['sex'] == 'female') & (titanic['class'] == 'First')]
survival_rate = female_first_class['survived'].mean()
overall_survival_rate = titanic['survived'].mean()

# Results
survival_rate, overall_survival_rate

(np.float64(0.9680851063829787), np.float64(0.3838383838383838))

Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [18]:

import pandas as pd
import seaborn as sns

# Load the Titanic dataset
titanic = sns.load_dataset('titanic')

# Fill missing age with median
titanic['age'] = titanic['age'].fillna(titanic['age'].median())

# Fill missing embarked with mode
titanic['embarked'] = titanic['embarked'].fillna(titanic['embarked'].mode()[0])

# Drop the deck column
titanic = titanic.drop(columns=['deck'])

# Identify missing values after filling
missing_values_after = titanic.isnull().sum()

# Results
missing_values_after

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [7]:
# Create family_size
titanic['family_size'] = titanic['sibsp'] + titanic['parch'] + 1

# Create is_alone feature
titanic['is_alone'] = (titanic['family_size'] == 1).astype(int)

# Compute survival rate by is_alone
survival_rate_alone = titanic.groupby('is_alone')['survived'].mean()

# Results
survival_rate_alone

is_alone
0    0.505650
1    0.303538
Name: survived, dtype: float64

Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [20]:
# Load Tips dataset
tips = sns.load_dataset('tips')

# Compute average tip by day
average_tip_by_day = tips.groupby('day', observed=True)['tip'].mean()

# Total bill by gender
total_bill_by_gender = tips.groupby('sex', observed=True)['total_bill'].sum()

# Create new feature: tip_percentage
tips['tip_percentage'] = (tips['tip'] / tips['total_bill']) * 100

# Identify which day has the highest tipping behavior
highest_tip_day = average_tip_by_day.idxmax()

# Results
average_tip_by_day, total_bill_by_gender, highest_tip_day

(day
 Thur    2.771452
 Fri     2.734737
 Sat     2.993103
 Sun     3.255132
 Name: tip, dtype: float64,
 sex
 Male      3256.82
 Female    1570.95
 Name: total_bill, dtype: float64,
 'Sun')

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [9]:
# Filter for total_bill > 20 and tip < 3
filtered_tips = tips[(tips['total_bill'] > 20) & (tips['tip'] < 3)]

# Select relevant columns
under_tipping = filtered_tips[['total_bill', 'tip']]

# Analyze under-tipping
is_under_tipping = under_tipping.shape[0]

# Results
is_under_tipping

21

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [10]:
# Create two arrays
array1 = np.array([[1, 2], [3, 4], [5, 6]])
array2 = np.array([[7, 8], [9, 10], [11, 12]])

# Perform vertical stacking
vert_stack = np.vstack((array1, array2))

# Perform horizontal stacking
horiz_stack = np.hstack((array1, array2))

# Reshape into (2, 6)
reshaped = vert_stack.reshape(2, 6)

# Results
vert_stack.shape, horiz_stack.shape, reshaped.shape

((6, 2), (3, 4), (2, 6))

Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [21]:
# Load Titanic dataset
titanic = sns.load_dataset('titanic')

# Fill missing age with median
titanic['age'] = titanic['age'].fillna(titanic['age'].median())

# Fill missing embarked with mode
titanic['embarked'] = titanic['embarked'].fillna(titanic['embarked'].mode()[0])

# Drop the deck column
titanic = titanic.drop(columns=['deck'])

# Encode categorical variables (sex and embarked)
titanic = pd.get_dummies(titanic, columns=['sex', 'embarked'], drop_first=True)

# Normalize numerical features (age and fare)
titanic[['age', 'fare']] = (titanic[['age', 'fare']] - titanic[['age', 'fare']].mean()) / titanic[['age', 'fare']].std()

# Convert to NumPy array
final_feature_matrix = titanic.drop(columns='survived').to_numpy()

# Results shape
final_feature_matrix.shape

(891, 14)

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [22]:
import numpy as np
import pandas as pd
from sklearn import datasets

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data  # Feature matrix as NumPy array
feature_names = iris.feature_names

# Compute correlation matrix
correlation_matrix = np.corrcoef(X, rowvar=False)

# Identify highly correlated features
threshold = 0.9
features_to_drop = []
for i in range(len(correlation_matrix)):
    for j in range(i+1, len(correlation_matrix)):
        if abs(correlation_matrix[i, j]) > threshold:
            features_to_drop.append(feature_names[j])  # Drop one of the correlated features

# Drop redundant features
# Assuming we keep features with lower index (earlier) over later ones
reduced_features = np.delete(X, [feature_names.index(f) for f in features_to_drop], axis=1)

# Results
features_to_drop

['petal width (cm)']

Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [13]:
# Create age_group feature
def age_group(age):
    if age < 18:
        return 'Child'
    elif age < 65:
        return 'Adult'
    else:
        return 'Senior'

titanic['age_group'] = titanic['age'].apply(age_group)

# Compute survival rate per group
survival_rate_by_age = titanic.groupby('age_group')['survived'].mean()

# Results
survival_rate_by_age

age_group
Child    0.383838
Name: survived, dtype: float64

Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [14]:
# Generate random error values
errors = np.random.normal(0, 1, 1000)

# Compute mean and standard deviation
mean_errors = np.mean(errors)
std_errors = np.std(errors)

# Identify outliers
outliers = errors[(errors < mean_errors - 2 * std_errors) | (errors > mean_errors + 2 * std_errors)]

# Results
mean_errors, std_errors, outliers.shape

(np.float64(-0.006829385346688115), np.float64(0.9839971935199621), (48,))

Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [23]:
# Load Tips dataset
tips = sns.load_dataset('tips')

# Create tip percentage
tips['tip_percentage'] = (tips['tip'] / tips['total_bill']) * 100

# Group by day and time to find the revenue segment
revenue_by_day_time = tips.groupby(['day', 'time'], observed=True)['total_bill'].sum().idxmax()

# Results
revenue_by_day_time

('Sat', 'Dinner')